name: stock
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - plotly
  - dash
  - dash-bootstrap-components
  - jupyter
  - jupyterlab
  - jupyter-dash
  - ipykernel
  - kaggle
  - pip
  - pip
  - pip:
      - gunicorn